### ISSUE TITLE
Mesecons do not open trapdoors

### ISSUE THREAD

**Issue by C1ffisme** [Jeija/minetest-mod-mesecons#213]
Basicaly, yeah. No more words needed. Yes, I do have the latest git.

**Comment by MT-Modder** [comment]
I'm going to work on this and submit a pull request if I succeed.

**Comment by C1ffisme** [comment]
Good. I'd make one myself, but I don't really feel like it.

**Comment by MT-Modder** [comment]
That's cool. I love doing this kinda stuff in my free time.

**Comment by MT-Modder** [comment]
Here it is if you want to check it out: https://github.com/Jeija/minetest-mod-mesecons/pull/214

**Comment by Jeija** [comment]
MT-Modder's changes have been merged with some modifications by me. Thanks MT-Modder for the code, and thanks C11ffisme for reporting the issue.

The original trapdoors code in minetest_game/doors/init.lua is really weird...
Like:
* `local tmp_node2` is never used anywhere, it's just a useless definition
* They do `local me = minetest.get_node(pos)`, even though they could have just passed `node` as an argument to `punch(pos)`:
```Lua
on_rightclick = function(pos, node, clicker)
	punch(pos)
end
```
* So much more random stuff, they don't need to use any minetest.get_meta() in order to make a trapdoor and the code is just longer than it needs to be

I think it's great if people that may not be as experienced coders as others do stuff, that's how everybody started. But how come this piece of code could end up in the official minetest_game that thousands of people use and houndreds of people look at...?? It's certainly not that much of a good learning resource.
I guess I need to fix some stuff there...

**Comment by MT-Modder** [comment]
@Jeija I agree 100%. There is so much redundant code in that mod. I kept '''tmp_node2''' in there in case I missed it somewhere else but in a quick review I didn't find it any where.
