### ISSUE TITLE
Pressure plates no longer open doors

### ISSUE THREAD

**Issue by mdoege** [Jeija/minetest-mod-mesecons#225]
Pressure plates no longer open doors since the doors rewrite: https://github.com/Jeija/minetest-mod-mesecons/commit/562cee7438ec43fd8e56eff3359326c54c7a6816

**Comment by Jeija** [comment]
It works just fine for me.
My test setup: I placed a stone pressure plate directly next to a wooden door on the floor and stepped on it. The door opened.
Please make sure you're using the latest version of
* minetest
* minetest_game
* minetest-mod-mesecons

and try to reproduce the issue. If it sill exists, please take a screenshot of your test setup or explain it in detail.

**Comment by mdoege** [comment]
You are right, it works correctly in a newly created world. In my Stampyworld map, Mesecons had turned itself off in the world settings for some reason.

So now doors open when I step on the pressure plate, but if I keep standing on it, the door opens and closes at about 1-second intervals in Stampyworld. I also see an error message: "The following mods could not be found: mesecons_compatibility"

The door constantly opening and closing when I stand on a pressure plate also happens in the newly created test world.

**Comment by Jeija** [comment]
mesecons_compatibility cannot be found because it was removed, the features are now in "mesecons_doors". Maybe you could try to re-enable the modpack in the mod menu? mesecons_doors should be enabled, while mesecons_compatibility shouldn't be there anymore. I'm not an expert on that though, I still install my mods the old-fashioned way by putting them in the game folder...

**Comment by mdoege** [comment]
Yes, I've reenabled it. But I don't think it was actually disabled. Because reverting Mesecons to a version before the doors rewrite fixed MT. If it had been really disabled it would not have been loaded at all from the global mods folder.

I have all other mods for Stampyworld in worldmods/, except Mesecons because it is so big and frequently updated.

Any thoughts on the doors opening and closing when standing on a pressure plate? It's very annoying and different from the old behavior (standing on pp == doors stays open).

**Comment by Jeija** [comment]
> Any thoughts on the doors opening and closing when standing on a pressure plate? It's very annoying and different from the old behavior (standing on pp == doors stays open).

Thanks for reporting that issue, that is actually a pressure plate issue and I just fixed it in aa5538a734.

**Comment by mdoege** [comment]
Great, so I guess my bug report was useful after all, even if it fixed an entirely separate bug. :-)

Perhaps my jumping back and foth between different MT git versions led to the "Mesecons disabled" issue? Very strange. Maybe I should include Mesecons with my map too, even if it bloats the ZIP file a bit.

Das MT-Forum wird ja in Deutschland gehostet, also dürfen wir seine Bandbreite verschwenden, korrekt? :-)

**Comment by mdoege** [comment]
P.S. Another bug: If you put two pressure plates next to a door, one before and one behind and walk across a few times, sometimes the door will "reverse", i.e. instead of being closed by default it will be open by default (and shut in your face when you step on the pressure plate).

**Comment by Jeija** [comment]
Unfortunately, that reverse-door bug is caused by limitations of the minetest engine, that won't allow me to use values lower than 1 for nodetimer timeouts, to allow checking more often for players moving, and I don't feel like coding even more workarounds to overcome these limitations.
A possibility would be to only allow reversing doors by right-clicking them, but that would restrict functionality. Maybe in the future.
I recommend you to use a different structure for doors that uses vertical mesecons. That way, you can also open double doors nicely and there shouldn't be any issue with reversing doors:
![screenshot_3479514699](https://cloud.githubusercontent.com/assets/1311964/6425583/46b9b43e-bf30-11e4-8ffd-59199865dc6b.png)

**Comment by mdoege** [comment]
I'am trying to emulate a MC map with my Stampyworld map, so I'd prefer to put pressue plates in the proper place (right next to the door block).

Has this door reversal problem existed before the doors rewrite too? I've never really noticed it before, but now it seems to be really bad, i.e. you just have way back and forth a few times and it will show up.
