### ISSUE TITLE
Doors problem

### ISSUE THREAD

**Issue by Ombridride** [Jeija/minetest-mod-mesecons#226]
Hi,

Since weeks ago, in the server MinetestForFun, we can't open doors with mesecons signals (pressure plaque, interruptor, etc...)

The server is updated with the latest minetest core version (latest update on 21 march 2015), the latest mesecons version (latest update on 20 march 2015), and the latest doors mod (latest update of the minetest_game repository)

Can you help us ? 
(If you want look at our github game : https://github.com/Ombridride/minetest-minetestforfun-server)

**Comment by Jeija** [comment]
I just downloaded https://github.com/Ombridride/minetest-minetestforfun-server, installed minetestforfun_game and copied the mods from the repo into minetestforfun_game/mods. I started the game and was able to open mesecons doors with both pressure plates and switches. Any other mods were disabled. So I obviously can't reproduce the issue.
Can you reproduce the bug on your local machine? If so, how?

**Comment by Ombridride** [comment]
it's strange, if i tried it in local with other mods, it doesn't work, and on the server, it's the same thing...

Maybe you want come and try in the server ?
address : qbuissondebon.info 
port : 30001
(login and password needed)

**Comment by LeMagnesium** [comment]
Mesecons wires aren't the problem, neither are pressure plates : the bug we detected was a door unabled to be opened by a meseblock connected in its right side with a **button** on the mese's face. @crabman77 (another of MinetestForFun's developers) thinks it's because the metadatas contained in the push button have not been updated. Do you have any thoughts about this idea?

**Comment by Jeija** [comment]
Mesecons uses hardly any metadata. I'm not sure what exactly what you built, but I guess it doesn't work because opening doors with a button on the right of it (like in minecraft) isn't implemented.

**Comment by LeMagnesium** [comment]
Our system is like this : 
![screenshot_1103287883](https://cloud.githubusercontent.com/assets/6785985/6769858/f097a074-d0ab-11e4-88d8-ed8faa31d456.png)
A few weeks ago it was working, then we updated, and it stopped working. However, a new system built on a local server works perfectly, that's why we thought about metadatas, because we need to pick up nodes and place them back to update these informations.

**Comment by Ombridride** [comment]
And, i can add, we have tried all others possibilities for linked a mesecons signal to a door and it doesn't work, the door doesn't open with all these possibilities...
(Before the update, every possibilities worked well)

**Comment by Ombridride** [comment]
Do you have a solution to our problems ?

**Comment by Ombridride** [comment]
Ok,
so we have been forced to return to a previous version of the mod for buttons and pressure plates with doors works again...

I think keep this issue ticket open isn't a bad idea, we will try again in a while to re-update mesecons...

**Comment by LeMagnesium** [comment]
> so we have been forced to return to a previous version of the mod for buttons and pressure plates  with doors works again...

Indeed. Yet, I tried something earlier : I upgraded mesecons to the last version, and added an old backup of mesecons_compatibility. Everything seemed to work perfectly. So the removed mod mesecons_compatibility caused our server to stop redefining the doors to work with mesecons.

**Comment by Ombridride** [comment]
The mistake was so stupid... After the update of the mod mesecons, we forget to activate the new mod into mesecons wich grant compatible doors...

You can close this issue, thank you for your time jeija
