### ISSUE TITLE
Mesecon Furnace?

### ISSUE THREAD

**Issue by amhadinger** [Jeija/minetest-mod-mesecons#260]
I'm not sure if this is a feature already, but could we make a furnace that is powered by mesecons?

**Comment by C1ffisme** [comment]
Yes, we could. And then we could put a lever next to the furnace, and use it as infinite fuel. No need for all those buckets of lava anymore... You can go ahead and turn those into obsidian too. And those pieces of coal are only useful for torches now, so start making all that coal into torches.

However, if you are talking about a furnace that could be turned off and on by mesecons, but requires fuel, I would love to see that.

**Comment by amhadinger** [comment]
No, I was talking about something like the Electric furnaces in the Technic mod. It would be cool though.

**Comment by MT-Modder** [comment]
I like the idea but fear it'll be OP.

**Comment by Jeija** [comment]
This doesn't really make sense to me - a furnace has to have a concept of power / energy required to heat an object and mesecons only has a concept of signals / information, no energy transfer. So this certainly makes more sense in the technic mod. I haven't really used that mod, but if it isn't already somehow possible, you could propably somehow add the ability to control the technic furnace with mesecons there.

Otherwise, if you still think this belongs in mesecons, feel free to create a mod that adds that furnace and publish it. If it gets enough attention from the community, it will be included in mesecons in the future. Adding mesecons support to the furnace should actually be pretty easy, see http://mesecons.net/developers.html.

**Comment by C1ffisme** [comment]
> I like the idea but fear it'll be OP.

My point exactly.

By the way, don't mesecons only work at 3.3 volts? That's quite low for an appliance that can cook bricks and refine ores.

**Comment by VanessaE** [comment]
I've always viewed mesecons like old-fashioned 74xx logic, e.g. 5v TTL.  The max fanout on old 'LS' family chips was only 10:1, with a total allowable power draw for all of the chip's outputs, combines, of 10 mA or thereabouts.  The heater on an electronic cigarette probably needs more power than that, to say nothing of trying to power a furnace with such a source.

I wouldn't resist the idea of a mesecons-controlled furnace, so long as it still needs a traditional fuel source to actually power it.

**Comment by Jeija** [comment]
There doesn't seem to be a lot of support for this idea; so if something like this is ever made, a separate mod or a modpack like [MoreMesecons](https://github.com/minetest-mods/MoreMesecons) will be a better home for this feature.
