### ISSUE TITLE
Official releases

### ISSUE THREAD

**Issue by SnarkBoojum** [Jeija/minetest-mod-mesecons#267]
Hi,

I plan to package mesecons in the Debian distribution ; but I'd rather package an official release than a random commit in the tree.

Can you tag a release?

Thanks!

**Comment by Jeija** [comment]
Thank you in advance for packaging!

I just removed two pdf / odt documentation files from the source tree (I don't think those should be included in a distribution package) and tagged the 2016.05.15 release. If the package is accepted by Debian I will continue to tag stable releases from now on. I'd like to use dates (YYYY.MM.DD) as versions due to the irregular update cycle of mesecons if that's alright with you.

**Comment by SnarkBoojum** [comment]
I think your version format will be perfect (something with dashes '-' would have been annoying). Thanks!

**Comment by SnarkBoojum** [comment]
Notice that by tagging releases like this, there are Debian Quality Assurance tools which will detect and notify me of new versions, so things should go pretty smoothly.
