### ISSUE TITLE
The "Switch" generates electricity

### ISSUE THREAD

**Issue by amadin** [Jeija/minetest-mod-mesecons#274]
Why need "Power Plant" if "Switch" generate electricity too?

**Comment by khonkhortisan** [comment]
One might want a lit wire that can't be turned off by other players. And it serves as the basis for the blinky plant. Mesecons is for low-level current appropriate for logic gates. A Power plant is more for what is supplied through power lines.  Ideally, a switch would connect a power source on one end to the rest of the circuit on the other end (should they be electrical wires instead of logic wires) Having both is a relic from when me second was the only wire system in the game, and was the go-to for both purposes. There are now wires for different power levels,  for message passing,  and for logic, but none yet that simulate a circuit board and the relative power of each wire segment.

**Comment by Jeija** [comment]
The Power Plant is not up for discussion. It was in mesecons from the very beginning, so removing it would destroy many circuits. It also has a minimal footprint in terms of code / nodes / file size.

When watching videos about mesecons / redstone on YouTube, you will constantly see people using mesecon / redstone torches to generate a high logic level on the cable for testing. Since the mesecon torch can interfere with other signals though (since it actually is meant to be an inverter), the power plant is a far better solution to this problem.

Also, the power plant is easier to craft than a switch, so it serves a purpose there.
