### ISSUE TITLE
Change of license for merge with MTGame

### ISSUE THREAD

**Issue by alexeysvrv** [Jeija/minetest-mod-mesecons#286]
Please change the license on lgpl version 2 with version 3, for the possibility of merging with MTGame(mesecons in MTGame). Thank you

**Comment by Jeija** [comment]
Unless there is a consensus that mesecons should even be merged into minetest_game, I'm not doing that - AFAIK I also can't do that on my own, I would have to reach out to past contributors in order to make this happen.

From what I've heard, bundling mesecons with mintest_game also isn't going to happen since mesecons is quite heavy in the number of nodes it registers.

**Comment by alexeysvrv** [comment]
@Jeija I propose to appeal to all participants to vote on changing the license. I think that all will vote only "for a change." And what about heaviness ... You can keep only the most necessary items (create a separate fork, which remove too much) ... By the way, mesecons has performance problems. FPS sags to 10-20, if you make a chopper (wire will periodically light up and go out)

**Comment by Jeija** [comment]
> You can keep only the most necessary items

No, wires are the most necessary items and they account for the vast majority of registered nodes. You should talk to the devs of minetest_game about this. Until they agree on this matter, I'm not changing any license.

**Comment by sofar** [comment]
FWIW, I'm against merging this mod and I'm not sure if it makes any sense, so I would certainly not relicense right now, only if there actually is some agreement on merging. So, I'm fully with @jeija on this.
