### ISSUE TITLE
Water turbine does not work with flowing river water

### ISSUE THREAD

**Issue by Wuzzy2** [Jeija/minetest-mod-mesecons#294]
The water turbine does not go on if flowing river water is going through.

IMO the water turbine should accept all “flowing” nodes as long they are in the group “water”. Or is it intentional that only the “normal” water is accepted?

**Comment by Jeija** [comment]
Absolutely agree, that is a bug.

I'm only posting it here, but this is for any of the other newly created issues as well: If someone sends in PRs for these issues, I will get them merged ASAP (these shouldn't take long to review, since it is mostly smaller issues).
If I don't get PRs, to be completely honest, mesecons is currently not on top of my priority list.
