### ISSUE TITLE
Pollution of global namespace.

### ISSUE THREAD

**Issue by beyondlimits** [Jeija/minetest-mod-mesecons#311]
I have found that mesecons mod leaks a lot of stuff to global namespace.

mesecons_delayer:
```
boxes
```
mesecons_extrawires:
```
crossover_get_rules
```
mesecons_microcontroller:
```
EEPROM_SIZE
groups
parse_get_command
parse_get_params
update_yc
yc_action
yc_action_setports
yc_code_remove_commentary
yc_command_after
yc_command_after_execute
yc_command_if
yc_command_if_getcondition
yc_command_off
yc_command_on
yc_command_parsecondition
yc_command_print
yc_command_sbi
yc_eeprom_read
yc_get_real_portstates
yc_get_virtual_portstates
yc_merge_portstates
yc_parse_get_eeprom_param
yc_parsecode
yc_reset
yc_set_portstate
yc_skip_to_else
yc_skip_to_endif
yc_update_real_portstates
```
mesecons_gates:
```
register_gate
```
mesecons_insulated:
```
insulated_wire_get_rules
```
mesecons_lamp:
```
mesecon_lamp_box
```
mesecons_pistons:
```
piston_facedir_direction
piston_get_direction
piston_rules
```
mesecons_pressureplates:
```
pp_on_timer
```
mesecons_wires:
```
register_wires
```
By the way, should mesecons own namespace be `mesecons` rather than `mesecon`?

**Comment by Jeija** [comment]
All of the namespace pollutions outside of `mesecons_microcontroller` have been fixed thanks to @sfan5. Since `mesecons_microcontroller` has been deprecated for a long time now and will get removed at some point, I'd consider this resolved.

The mesecons namespace has been `mesecon` since pretty much forever, so I don't think we should change that since other mods may even depend on it.

Thanks for reporting!

**Comment by sfan5** [comment]
Thought I'd fix `mesecons_microcontroller` too since I'm still using it and it's not too complicated.
